# Generated by Django 5.0.2 on 2024-07-11 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklist', '0001_initial'),
        ('collateralemployee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral_EmployeeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(blank=True, max_length=25, null=True)),
                ('fileUrl', models.FileField(blank=True, null=True, upload_to='lps_django_2024/uploads/')),
                ('uploadedAt', models.DateField(auto_now_add=True)),
                ('amDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('isUploaded', models.BooleanField(default=False)),
                ('isMandatory', models.BooleanField(default=True)),
                ('checkListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeefileschecklist', to='checklist.checklist')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaryfiles', to='collateralemployee.collateral_employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collateralemployeeuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
