# Generated by Django 5.0.2 on 2024-07-11 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('subcity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpauseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amFullName', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=15)),
                ('mobileNo', models.CharField(max_length=15)),
                ('woreda', models.CharField(blank=True, max_length=255, null=True)),
                ('amWoreda', models.CharField(blank=True, max_length=255, null=True)),
                ('houseNum', models.CharField(blank=True, max_length=255, null=True)),
                ('idNum', models.CharField(blank=True, max_length=255, null=True)),
                ('monthlyIncome', models.FloatField(blank=True, max_length=255, null=True)),
                ('amSubcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spausesubcity', to='subcity.subcity')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spausedetail', to='customer.customer')),
            ],
            options={
                'unique_together': {('mobileNo', 'amFullName')},
            },
        ),
    ]
