# Generated by Django 5.0.2 on 2024-07-11 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobposition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enFullName', models.CharField(max_length=255)),
                ('amFullName', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('jobposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposition', to='jobposition.jonbposition')),
            ],
        ),
    ]
