# Generated by Django 4.2.7 on 2024-07-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loancommittee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loancommittee',
            old_name='jobposition',
            new_name='parent',
        ),
    ]
