# Generated by Django 4.2.7 on 2024-07-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanGuaranteePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMarried', models.BooleanField()),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('subcity', models.CharField(max_length=255, null=True)),
                ('woreda', models.CharField(max_length=255, null=True)),
                ('housenum', models.CharField(max_length=255, null=True)),
                ('idnum', models.CharField(max_length=255, null=True)),
                ('phonenum', models.CharField(max_length=255, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp', to='loan.loan')),
            ],
        ),
    ]
