# Generated by Django 4.2.7 on 2024-06-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayName', models.CharField(max_length=255)),
                ('holyDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
