# Generated by Django 5.0.2 on 2024-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enName', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('id', 'enName')},
            },
        ),
    ]
