# Generated by Django 4.2.7 on 2024-07-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklisttype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enName', models.CharField(blank=True, max_length=255, null=True)),
                ('amName', models.CharField(max_length=255)),
                ('isMandatory', models.BooleanField(default=True)),
                ('markValue', models.IntegerField(default=5)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklisttype.checklisttype')),
            ],
            options={
                'unique_together': {('parent', 'enName', 'amName')},
            },
        ),
    ]
