# Generated by Django 4.2.7 on 2024-07-19 02:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='financeCheking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='financeapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='financeat',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='financeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursefinance', to=settings.AUTH_USER_MODEL),
        ),
    ]
