# Generated by Django 4.2.7 on 2024-06-11 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='queueDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
