# Generated by Django 4.2.7 on 2024-07-07 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carmanufacturer', '0001_initial'),
        ('subcity', '0001_initial'),
        ('checklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0001_initial'),
        ('carmodel', '0001_initial'),
        ('loanguaranteeperson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassisNumber', models.CharField(max_length=255)),
                ('engineNumber', models.CharField(max_length=255)),
                ('librebookid', models.CharField(max_length=255)),
                ('carPlate', models.CharField(max_length=255)),
                ('insuranceValue', models.FloatField(default=0)),
                ('carCC', models.IntegerField()),
                ('isApproved', models.BooleanField(default=False)),
                ('approvedAt', models.DateField(blank=True, null=True)),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedCar', to=settings.AUTH_USER_MODEL)),
                ('cargp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cargp', to='loanguaranteeperson.loanguaranteeperson')),
                ('checkListId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmanufacturecountry', to='checklist.checklist')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateralcar', to='loan.loan')),
                ('manufacturedYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmanufacture', to='carmanufacturer.car_manufacture')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodel', to='carmodel.car_model')),
                ('subcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsubcity', to='subcity.subcity')),
            ],
        ),
    ]
