# Generated by Django 4.2.7 on 2024-07-05 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disbursement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='approvedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='disbursedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='plannedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
