# Generated by Django 4.2.7 on 2024-07-05 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disbursement', '0002_alter_disbursement_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='checkId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='checkSignedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checksignedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='checkSignedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_detail', to='loan.loan'),
        ),
    ]
