# Generated by Django 4.2.7 on 2024-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enName', models.CharField(max_length=255)),
                ('amName', models.CharField(max_length=255)),
                ('pricepercaremeter', models.IntegerField()),
            ],
            options={
                'unique_together': {('enName', 'amName')},
            },
        ),
    ]
