# Generated by Django 5.0.2 on 2024-07-11 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enName', models.CharField(max_length=255)),
                ('amName', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woredas', to='subcity.subcity')),
            ],
            options={
                'unique_together': {('parent', 'enName', 'amName')},
            },
        ),
    ]
