
# POST https://solomon41411.pythonanywhere.com/lpsauth/registerall
POST http://localhost:8000/lpsauth/registerall
Content-Type: application/json

[
    {
        "username": "rediet",
        "email": "rediet@gmail.com",
        "password": "P@55w0rd",
        "first_name":"ረደኤት",
        "last_name":"አባት",
        "groups":"ROLE_OFFICER",
        "is_active": "true"
    },
     {
        "username": "officer2",
        "email": "officer2@gmail.com",
        "password": "P@55w0rd",
        "first_name":"ኦፊሰር-2",
        "last_name":"አባት",
        "groups":"ROLE_OFFICER",
        "is_active": "true"
    },
     {
        "username": "officer3",
        "email": "officer3@gmail.com",
        "password": "P@55w0rd",
        "first_name":"ኦፊሰር-3",
        "last_name":"አባት",
        "groups":"ROLE_OFFICER",
        "is_active": "true"
    },
     {
        "username": "finance",
        "email": "finance@gmail.com",
        "password": "P@55w0rd",
        "first_name":"finance",
        "last_name":"አባት",
        "groups":"ROLE_FINANCE",
        "is_active": "true"
    },
     {
        "username": "hagos",
        "email": "hagos@gmail.com",
        "password": "P@55w0rd",
        "first_name":"hagos",
        "last_name":"አባት",
        "groups":"ROLE_TEAM_LEADER",
        "is_active": "true"
    },
    {
        "username": "liwam",
        "email": "liwam@gmail.com",
        "password": "P@55w0rd",
        "first_name":"ልዋም",
        "last_name":"አባት",
        "groups":"ROLE_AUDITOR",
        "is_active": "true"
    },
    {
        "username": "adugna",
        "email": "adugna@gmail.com",
        "password": "P@55w0rd",
        "first_name":"አዱኛ",
        "last_name":"አባት",
        "groups":"ROLE_PLANNER",
        "is_active": "true"
    },
     {
        "username": "admin",
        "email": "admin@gmail.com",
        "password": "P@55w0rd",
        "first_name":"አስተዳደር",
        "last_name":"አባት",
        "groups":"ROLE_ADMIN",
        "is_active": "true"
    } 
]


##### 
POST http://localhost:8000/lpsauth/register
Content-Type: application/json

   {
        "username": "alem",
        "email": "alem@gmail.com",
        "password": "P@55w0rd",
        "first_name":"alem",
        "last_name":"alem",
        "groups":"ROLE_APPLICANT",
        "is_active": "false"
    }

