# Generated by Django 4.2.7 on 2024-07-30 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('withdrawaldetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawaldetail',
            old_name='isDisbursed',
            new_name='isAccepted',
        ),
        migrations.RemoveField(
            model_name='withdrawaldetail',
            name='disbursedby',
        ),
        migrations.AddField(
            model_name='withdrawaldetail',
            name='acceptedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawalacceptedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawaldetail',
            name='acceptedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawaldetail',
            name='deliveredBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawalddeliveredby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawaldetail',
            name='deliveredDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawaldetail',
            name='isDelivered',
            field=models.BooleanField(default=False),
        ),
    ]
