# Generated by Django 4.2.7 on 2024-07-19 02:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('externalId', models.CharField(blank=True, max_length=15, null=True)),
                ('loanSavingSum', models.FloatField(blank=True, default=0, null=True)),
                ('voluntarySum', models.FloatField(blank=True, default=0, null=True)),
                ('funeralSum', models.FloatField(blank=True, default=0, null=True)),
                ('compulsarySum', models.FloatField(blank=True, default=0, null=True)),
                ('timeDepositSum', models.FloatField(blank=True, default=0, null=True)),
                ('totalSaving', models.FloatField()),
                ('totalShares', models.FloatField()),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('entityAccountNo', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=255)),
                ('amDisplayName', models.CharField(max_length=255)),
                ('entityMobileNo', models.CharField(max_length=15)),
                ('financeCheking', models.BooleanField(default=False)),
                ('financeapproved', models.BooleanField(default=False)),
                ('financeat', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('financeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawfinance', to=settings.AUTH_USER_MODEL)),
                ('plannedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawplannedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
