# Generated by Django 4.2.7 on 2024-07-27 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('withdrawcustomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('savingType', models.CharField(max_length=255)),
                ('amSavingType', models.CharField(max_length=255)),
                ('customerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tobewithdrawen', to='withdrawcustomer.withdrawcustomer')),
            ],
        ),
    ]
