# Generated by Django 4.2.7 on 2024-06-09 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0001_initial'),
        ('hometype', '0001_initial'),
        ('loanguaranteeperson', '0001_initial'),
        ('subcity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollateralHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationtxt', models.CharField(max_length=255)),
                ('bldgno', models.CharField(blank=True, max_length=255, null=True)),
                ('floorno', models.CharField(blank=True, max_length=255, null=True)),
                ('woreda', models.CharField(max_length=255)),
                ('houseno', models.CharField(max_length=255)),
                ('uniquenum', models.CharField(max_length=255)),
                ('amName', models.CharField(max_length=255)),
                ('homearea', models.FloatField()),
                ('createdAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collateralhomeinsertedby', to=settings.AUTH_USER_MODEL)),
                ('homegp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='homegp', to='loanguaranteeperson.loanguaranteeperson')),
                ('hometype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometype', to='hometype.hometype')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateralhome', to='loan.loan')),
                ('subcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homesubcity', to='subcity.subcity')),
            ],
        ),
    ]
